export { default as Center } from './Center'
export { Chapter, Section, Title, FullScreen, ClosingSlide } from './Section'
export { ColorText, Danger, Success, Vv } from './ColorText'
export { default as SVG } from './SVG'
export { default as ColorBox } from './ColorBox'
export { TODO } from './TODO'
export { default as CenteredText } from './CenteredText'
export { default as CaptionedImage } from './CaptionedImage'
export { default as Relative } from './Relative'
export { default as HandsOn } from './HandsOn'
export { default as Iframe } from './Iframe'
export { OneAtATime } from './OneAtATime'
export { Appear } from 'mdx-deck'

export { Embed } from 'gatsby-theme-mdx-deck/src/components/embed.js'
export { Notes } from 'gatsby-theme-mdx-deck/src/components/notes.js'
export { Head } from 'gatsby-theme-mdx-deck/src/components/head.js'

export { default as Horizontal } from '../gatsby-theme-mdx-deck/components/horizontal.js'
export { default as Image } from '../gatsby-theme-mdx-deck/components/image.js'
